import { useEffect, useMemo, useState } from "react";
import {
  AlertTriangle,
  BarChart3,
  BookOpen,
  Boxes,
  Check,
  Copy,
  FileText,
  GitBranch,
  Info,
  LayoutDashboard,
  Loader2,
  Network,
  Package,
  RefreshCw,
  ShieldAlert,
  Sparkles,
  Workflow,
  Zap,
} from "lucide-react";
import type { ProjectAnalysis, SecurityFinding, Tab } from "../lib/types";
import { fmtBytes, fmtCount, fmtTime } from "../lib/store";
import { Markdown } from "../lib/markdown";
import { buildMermaid } from "../lib/recon/mermaid";
import { offlineArchitecture, offlineQuality } from "../lib/recon/offline";
import { Badge, Btn, Card, Chip, EmptyState, SectionTitle, Spinner, Stat, cn } from "./ui";

// ---------------------------------------------------------------------------
// Shared bits
// ---------------------------------------------------------------------------

function AiSectionCard({
  content,
  model,
  generatedAt,
}: {
  content: string;
  model?: string;
  generatedAt: number;
}) {
  return (
    <Card className="p-5">
      <div className="mb-3 flex items-center justify-between">
        <div className="flex items-center gap-1.5 text-[11px] text-zinc-500">
          <Sparkles size={12} className="text-gold-400" />
          Generated by {model ?? "AI"} · {fmtTime(generatedAt)}
        </div>
      </div>
      <Markdown md={content} className="md" />
    </Card>
  );
}

function GenerateBanner({
  label,
  offline,
  onGenerate,
  busy,
  hasKey,
  onOpenSettings,
  children,
}: {
  label: string;
  offline: string;
  onGenerate: () => void;
  busy: boolean;
  hasKey: boolean;
  onOpenSettings: () => void;
  children?: React.ReactNode;
}) {
  return (
    <div className="space-y-4">
      <Card className="p-5">
        <div className="mb-3 flex items-center justify-between">
          <div className="flex items-center gap-1.5 text-[11px] text-zinc-500">
            <Zap size={12} className="text-gold-400" />
            Local heuristic preview — not AI-generated
          </div>
          {!hasKey && (
            <button onClick={onOpenSettings} className="text-[11px] text-amber-300/90 underline-offset-2 hover:underline">
              Add an AI key
            </button>
          )}
        </div>
        <Markdown md={offline} className="md opacity-90" />
      </Card>
      {children}
      <div className="flex items-center gap-3">
        <Btn variant="primary" icon={busy ? <Spinner size={15} /> : <Sparkles size={15} />} onClick={onGenerate} disabled={busy || (!hasKey && false)}>
          {busy ? "Generating…" : `Generate ${label} with AI`}
        </Btn>
        {!hasKey && (
          <span className="text-[12px] text-zinc-500">
            No API key set — <button className="text-gold-300 underline-offset-2 hover:underline" onClick={onOpenSettings}>open Settings</button> to connect OpenRouter (or Ollama locally).
          </span>
        )}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Overview
// ---------------------------------------------------------------------------

function LangBar({ name, files, confidence, color }: { name: string; files: number; confidence: number; color: string }) {
  return (
    <div className="flex items-center gap-3">
      <span className="h-2.5 w-2.5 shrink-0 rounded-sm" style={{ background: color }} />
      <span className="w-44 shrink-0 truncate text-[13px] text-zinc-200">{name}</span>
      <div className="h-1.5 min-w-0 flex-1 overflow-hidden rounded-full bg-white/8">
        <div className="h-full rounded-full" style={{ width: `${Math.min(100, files)}%`, background: color }} />
      </div>
      <span className="w-14 shrink-0 text-right text-[11px] tabular-nums text-zinc-500">{files}</span>
      <span className="w-12 shrink-0 text-right text-[11px] tabular-nums text-zinc-500">{Math.round(confidence * 100)}%</span>
    </div>
  );
}

function OverviewView({ a }: { a: ProjectAnalysis }) {
  const maxLang = Math.max(1, ...a.languages.map((l) => l.files));
  return (
    <div className="animate-fadeUp space-y-5">
      <Card className="p-5">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <h1 className="text-xl font-bold text-zinc-100">{a.name}</h1>
            <div className="mt-1 flex flex-wrap items-center gap-2">
              <Badge tone="gold">{a.label}</Badge>
              <Badge>{fmtTime(a.importedAt)}</Badge>
              <Badge tone="blue">{fmtCount(a.fileCount)} files</Badge>
              <Badge tone="green">{fmtBytes(a.totalSize)}</Badge>
            </div>
          </div>
        </div>
        {a.readmePreview && (
          <div className="mt-4 rounded-xl border border-white/8 bg-white/[0.02] p-4">
            <div className="mb-1.5 flex items-center gap-1.5 text-[11px] font-medium uppercase tracking-wider text-zinc-500">
              <BookOpen size={12} /> README preview
            </div>
            <pre className="whitespace-pre-wrap font-mono text-[12px] leading-relaxed text-zinc-400">
              {a.readmePreview.slice(0, 1200)}
            </pre>
          </div>
        )}
      </Card>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <Stat label="Source files" value={fmtCount(a.fileCount)} icon={<FileText size={13} />} />
        <Stat label="Languages" value={a.languages.length} sub={a.languages.slice(0, 3).map((l) => l.name).join(", ")} icon={<LayoutDashboard size={13} />} />
        <Stat label="Frameworks" value={a.frameworks.length} sub={a.frameworks.slice(0, 3).map((f) => f.name).join(", ") || "none"} icon={<Network size={13} />} />
        <Stat label="Dependencies" value={a.depSummary.runtime + a.depSummary.dev} sub={`${a.depSummary.runtime} runtime · ${a.depSummary.dev} dev`} icon={<Package size={13} />} />
      </div>

      {a.sourceMeta && (
        <Card className="p-5">
          <SectionTitle icon={<Info size={14} />} title="Source metadata" />
          <div className="grid grid-cols-1 gap-x-8 gap-y-1.5 sm:grid-cols-2">
            {Object.entries(a.sourceMeta).map(([k, v]) => (
              <div key={k} className="flex justify-between gap-3 border-b border-white/5 py-1.5 text-[13px]">
                <span className="text-zinc-500">{k}</span>
                <span className="max-w-[70%] truncate text-right text-zinc-200" title={v}>{v}</span>
              </div>
            ))}
          </div>
        </Card>
      )}

      <div className="grid gap-4 lg:grid-cols-2">
        <Card className="p-5">
          <SectionTitle icon={<FileText size={14} />} title="Languages" right={<span className="text-[11px] text-zinc-600">confidence</span>} />
          <div className="space-y-2.5">
            {a.languages.length ? (
              a.languages.map((l) => (
                <LangBar key={l.name} name={l.name} files={l.files} confidence={l.confidence} color={l.color} />
              ))
            ) : (
              <p className="text-[13px] text-zinc-500">No source languages detected.</p>
            )}
          </div>
        </Card>

        <Card className="p-5">
          <SectionTitle icon={<Sparkles size={14} />} title="Frameworks & runtimes" />
          {a.frameworks.length ? (
            <div className="flex flex-wrap gap-2">
              {a.frameworks.map((f) => (
                <Chip key={f.name} active={f.confidence >= 0.9}>
                  {f.name}
                  <span className="text-[10px] opacity-70">{Math.round(f.confidence * 100)}%</span>
                </Chip>
              ))}
            </div>
          ) : (
            <p className="text-[13px] text-zinc-500">No frameworks confidently detected.</p>
          )}
        </Card>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Card className="p-5">
          <SectionTitle icon={<GitBranch size={14} />} title="Entry points" />
          {a.entryPoints.length ? (
            <ul className="space-y-1.5">
              {a.entryPoints.map((e) => (
                <li key={e} className="rounded-lg bg-white/[0.03] px-3 py-1.5 font-mono text-[12px] text-zinc-300">{e}</li>
              ))}
            </ul>
          ) : (
            <p className="text-[13px] text-zinc-500">None detected.</p>
          )}
        </Card>

        <Card className="p-5">
          <SectionTitle icon={<Boxes size={14} />} title="Build systems" />
          <div className="flex flex-wrap gap-2">
            {a.buildSystems.length ? a.buildSystems.map((b) => <Badge key={b} tone="blue">{b}</Badge>) : <Badge>none</Badge>}
          </div>
          <div className="mt-4">
            <SectionTitle icon={<FileText size={14} />} title="Key config files" />
            <div className="flex flex-wrap gap-1.5">
              {a.configFiles.length ? (
                a.configFiles.slice(0, 20).map((c) => (
                  <span key={c} className="rounded-md bg-white/[0.04] px-2 py-0.5 font-mono text-[11px] text-zinc-400">{c}</span>
                ))
              ) : (
                <span className="text-[13px] text-zinc-500">None.</span>
              )}
            </div>
          </div>
        </Card>
      </div>

      {a.notes.length > 0 && (
        <Card className="border-amber-500/20 bg-amber-500/[0.04] p-5">
          <SectionTitle icon={<Info size={14} />} title="Notes" />
          <ul className="space-y-1 text-[13px] text-zinc-400">
            {a.notes.map((n, i) => <li key={i}>• {n}</li>)}
          </ul>
        </Card>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Architecture
// ---------------------------------------------------------------------------

function ArchitectureView({
  a,
  onGenerate,
  busy,
  hasKey,
  onOpenSettings,
  onGenerateReadme,
  readmeBusy,
}: {
  a: ProjectAnalysis;
  onGenerate: () => void;
  busy: boolean;
  hasKey: boolean;
  onOpenSettings: () => void;
  onGenerateReadme: () => void;
  readmeBusy: boolean;
}) {
  return (
    <div className="animate-fadeUp space-y-4">
      {a.architecture ? (
        <>
          <div className="flex items-center justify-between">
            <AiSectionCard content={a.architecture.content} model={a.architecture.model} generatedAt={a.architecture.generatedAt} />
          </div>
          <div className="flex gap-2">
            <Btn icon={<RefreshCw size={14} />} onClick={onGenerate} disabled={busy}>
              {busy ? "Generating…" : "Regenerate"}
            </Btn>
          </div>
        </>
      ) : (
        <GenerateBanner
          label="architecture analysis"
          offline={offlineArchitecture(a)}
          onGenerate={onGenerate}
          busy={busy}
          hasKey={hasKey}
          onOpenSettings={onOpenSettings}
        >
          {a.readme ? (
            <Card className="p-5">
              <div className="mb-2 flex items-center justify-between">
                <div className="flex items-center gap-1.5 text-[11px] text-zinc-500">
                  <BookOpen size={12} className="text-gold-400" /> Generated README
                </div>
                <Badge tone="gold">{a.readme.model}</Badge>
              </div>
              <Markdown md={a.readme.content} className="md" />
            </Card>
          ) : (
            <div className="flex items-center gap-3">
              <Btn icon={readmeBusy ? <Spinner size={14} /> : <BookOpen size={14} />} onClick={onGenerateReadme} disabled={readmeBusy}>
                {readmeBusy ? "Writing README…" : "Generate README.md"}
              </Btn>
              <span className="text-[12px] text-zinc-500">Install steps, structure, features & usage.</span>
            </div>
          )}
        </GenerateBanner>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Dependencies
// ---------------------------------------------------------------------------

function DepsView({ a }: { a: ProjectAnalysis }) {
  const [filter, setFilter] = useState("");
  const deps = useMemo(() => {
    const q = filter.toLowerCase();
    const list = q
      ? a.deps.filter((d) => d.name.toLowerCase().includes(q) || d.manifest.toLowerCase().includes(q))
      : a.deps;
    return list.slice(0, 300);
  }, [a.deps, filter]);
  const s = a.depSummary;
  return (
    <div className="animate-fadeUp space-y-4">
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <Stat label="Runtime deps" value={s.runtime} icon={<Package size={13} />} />
        <Stat label="Dev deps" value={s.dev} icon={<Boxes size={13} />} />
        <Stat label="Unpinned" value={s.unpinned.length} sub="no exact version" icon={<AlertTriangle size={13} />} />
        <Stat label="Duplicates" value={s.duplicates.length} sub="across manifests" icon={<RefreshCw size={13} />} />
      </div>

      {s.heavyManifests.length > 0 && (
        <Card className="border-amber-500/20 bg-amber-500/[0.04] p-4">
          <div className="text-[12px] font-medium text-amber-200">Heavy manifests ({s.heavyManifests.length})</div>
          <div className="mt-1 text-[12px] text-zinc-400">{s.heavyManifests.join(" · ")} — consider splitting or trimming.</div>
        </Card>
      )}

      <Card className="p-5">
        <SectionTitle icon={<Boxes size={14} />} title="Manifests" />
        <div className="overflow-x-auto">
          <table className="w-full text-[13px]">
            <thead>
              <tr className="border-b border-white/8 text-left text-[11px] uppercase tracking-wider text-zinc-500">
                <th className="py-2 pr-4">Manifest</th>
                <th className="py-2 pr-4">Type</th>
                <th className="py-2 pr-4 text-right">Runtime</th>
                <th className="py-2 pr-4 text-right">Dev</th>
                <th className="py-2 text-right">Total</th>
              </tr>
            </thead>
            <tbody>
              {s.byManifest.map((m) => (
                <tr key={m.manifest} className="border-b border-white/5">
                  <td className="py-2 pr-4 font-mono text-[12px] text-zinc-200">{m.manifest}</td>
                  <td className="py-2 pr-4 text-zinc-500">{m.kind}</td>
                  <td className="py-2 pr-4 text-right tabular-nums text-zinc-300">{m.runtime}</td>
                  <td className="py-2 pr-4 text-right tabular-nums text-zinc-300">{m.dev}</td>
                  <td className="py-2 text-right font-medium tabular-nums text-gold-300">{m.total}{m.parseError ? <span className="ml-1 text-[10px] text-red-400">error</span> : null}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      <Card className="p-5">
        <SectionTitle
          icon={<Package size={14} />}
          title={`Dependencies (${a.deps.length})`}
          right={
            <input
              value={filter}
              onChange={(e) => setFilter(e.target.value)}
              placeholder="Filter…"
              className="rounded-lg border border-white/10 bg-ink-800 px-2.5 py-1 text-[12px] text-zinc-200 placeholder-zinc-600 outline-none focus:border-gold-500/50"
            />
          }
        />
        {deps.length ? (
          <div className="max-h-[420px] overflow-y-auto">
            <table className="w-full text-[12.5px]">
              <thead className="sticky top-0 bg-ink-850">
                <tr className="border-b border-white/8 text-left text-[11px] uppercase tracking-wider text-zinc-500">
                  <th className="py-2 pr-4">Package</th>
                  <th className="py-2 pr-4">Version</th>
                  <th className="py-2 pr-4">Kind</th>
                  <th className="py-2">Manifest</th>
                </tr>
              </thead>
              <tbody>
                {deps.map((d, i) => (
                  <tr key={`${d.manifest}-${d.name}-${i}`} className="border-b border-white/5 hover:bg-white/[0.02]">
                    <td className="py-1.5 pr-4 font-mono text-zinc-200">{d.name}</td>
                    <td className="py-1.5 pr-4 font-mono text-zinc-400">{d.version}{d.pinned ? null : <span className="ml-1 rounded bg-amber-500/10 px-1 text-[9px] text-amber-300">loose</span>}</td>
                    <td className="py-1.5 pr-4"><Badge tone={d.kind === "dev" ? "blue" : "green"}>{d.kind}</Badge></td>
                    <td className="py-1.5 font-mono text-[11px] text-zinc-500">{d.manifest}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <EmptyState icon={<Package size={22} />} title="No dependencies" body="No supported dependency manifests were found in this project." />
        )}
      </Card>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Diagram
// ---------------------------------------------------------------------------

function DiagramView({ a }: { a: ProjectAnalysis }) {
  const code = useMemo(() => buildMermaid(a), [a]);
  const [svg, setSvg] = useState<string | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let alive = true;
    // Mermaid is ~700 KB, so it is loaded lazily only when this tab opens.
    (async () => {
      try {
        const m = (await import("mermaid")).default;
        m.initialize({
          startOnLoad: false,
          theme: "dark",
          securityLevel: "strict",
          fontFamily: "Inter, system-ui, sans-serif",
          themeVariables: {
            primaryColor: "#1C1A10",
            primaryTextColor: "#E8C15A",
            primaryBorderColor: "#D4AF37",
            lineColor: "#D4AF37",
            secondaryColor: "#101820",
            tertiaryColor: "#0F1A12",
            background: "#0A0A0F",
            mainBkg: "#12121A",
            nodeBorder: "#3A3A4C",
            clusterBkg: "#12121A",
            clusterBorder: "#3A3A4C",
          },
        });
        const { svg } = await m.render(`mmd-${a.id}`, code);
        if (alive) {
          setSvg(svg);
          setErr(null);
        }
      } catch (e) {
        if (alive) {
          setErr(e instanceof Error ? e.message : String(e));
          setSvg(null);
        }
      }
    })();
    return () => {
      alive = false;
    };
  }, [code, a.id]);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      /* clipboard unavailable */
    }
  };

  return (
    <div className="animate-fadeUp space-y-4">
      <Card className="overflow-hidden p-5">
        <SectionTitle
          icon={<Workflow size={14} />}
          title="Module relationship map"
          right={
            <div className="flex gap-2">
              <Btn size="sm" icon={copied ? <Check size={12} /> : <Copy size={12} />} onClick={copy}>
                {copied ? "Copied" : "Copy Mermaid"}
              </Btn>
              <Btn size="sm" icon={<FileText size={12} />} onClick={() => {
                const blob = new Blob([code], { type: "text/plain" });
                const url = URL.createObjectURL(blob);
                const el = document.createElement("a");
                el.href = url;
                el.download = `${a.name.replace(/[^\w.-]+/g, "_")}.mmd`;
                el.click();
                setTimeout(() => URL.revokeObjectURL(url), 3000);
              }}>
                Download .mmd
              </Btn>
            </div>
          }
        />
        <div className="rounded-xl border border-white/5 bg-ink-950/60 p-4">
          {err ? (
            <div className="space-y-3">
              <div className="rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-[12px] text-red-200">
                Mermaid failed to render: {err}
              </div>
              <pre className="overflow-x-auto rounded-lg bg-ink-950 p-3 font-mono text-[11px] text-zinc-400">{code}</pre>
            </div>
          ) : svg ? (
            <div className="flex justify-center overflow-x-auto" dangerouslySetInnerHTML={{ __html: svg }} />
          ) : (
            <div className="flex items-center justify-center py-16 text-zinc-500">
              <Loader2 size={20} className="animate-spin text-gold-400" />
            </div>
          )}
        </div>
        <p className="mt-3 text-[11px] leading-relaxed text-zinc-600">
          Edges are inferred from folder naming conventions (e.g. <code className="text-zinc-400">api → models</code>),
          not from import analysis. Use it as an orientation aid, then ask the assistant for specifics.
        </p>
      </Card>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Security
// ---------------------------------------------------------------------------

const SEV_TONE: Record<SecurityFinding["severity"], "red" | "amber" | "blue" | "gray"> = {
  high: "red",
  medium: "amber",
  low: "blue",
  info: "gray",
};

function SecurityView({ a }: { a: ProjectAnalysis }) {
  const counts = {
    high: a.security.filter((f) => f.severity === "high").length,
    medium: a.security.filter((f) => f.severity === "medium").length,
    low: a.security.filter((f) => f.severity === "low").length,
    info: a.security.filter((f) => f.severity === "info").length,
  };
  return (
    <div className="animate-fadeUp space-y-4">
      <div className="flex items-center gap-2 rounded-xl border border-amber-500/25 bg-amber-500/[0.06] px-4 py-3 text-[12px] leading-relaxed text-amber-100/90">
        <ShieldAlert size={15} className="shrink-0 text-amber-300" />
        <span>
          Heuristic, pattern-based findings only — not a security guarantee. Real secrets should be
          rotated and revoked; always verify findings manually before acting on them.
        </span>
      </div>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <Stat label="High" value={counts.high} icon={<AlertTriangle size={13} />} sub="credentials/secrets" />
        <Stat label="Medium" value={counts.medium} icon={<ShieldAlert size={13} />} sub="config & tokens" />
        <Stat label="Low" value={counts.low} icon={<Info size={13} />} sub="debug & hygiene" />
        <Stat label="Files scanned" value={a.scanStats.filesScanned} icon={<FileText size={13} />} sub={`${fmtBytes(a.scanStats.bytesScanned)} sampled`} />
      </div>

      {a.security.length ? (
        <Card className="divide-y divide-white/5">
          {a.security.map((f, i) => (
            <div key={i} className="flex gap-3 p-4">
              <span className={cn("mt-1.5 h-2 w-2 shrink-0 rounded-full", {
                high: "bg-red-400 shadow-[0_0_8px_rgba(248,113,113,0.6)]",
                medium: "bg-amber-400",
                low: "bg-sky-400",
                info: "bg-zinc-500",
              }[f.severity])} />
              <div className="min-w-0 flex-1">
                <div className="flex flex-wrap items-center gap-2">
                  <Badge tone={SEV_TONE[f.severity]}>{f.severity}</Badge>
                  <Badge>{f.category}</Badge>
                  {f.file && (
                    <span className="font-mono text-[11px] text-zinc-500">
                      {f.file}
                      {f.line ? <span className="text-gold-400">:{f.line}</span> : null}
                    </span>
                  )}
                </div>
                <div className="mt-1 text-[13px] text-zinc-200">{f.message}</div>
                {f.evidence && (
                  <code className="mt-1.5 block truncate rounded-md bg-ink-950/70 px-2 py-1 font-mono text-[11px] text-gold-200/80" title={f.evidence}>
                    {f.evidence}
                  </code>
                )}
              </div>
            </div>
          ))}
        </Card>
      ) : (
        <EmptyState
          icon={<ShieldAlert size={22} />}
          title="No findings"
          body="No obvious secrets, credentials or risky patterns found in the sampled files."
        />
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Quality
// ---------------------------------------------------------------------------

function QualityView({
  a,
  onGenerate,
  busy,
  hasKey,
  onOpenSettings,
}: {
  a: ProjectAnalysis;
  onGenerate: () => void;
  busy: boolean;
  hasKey: boolean;
  onOpenSettings: () => void;
}) {
  return (
    <div className="animate-fadeUp space-y-4">
      {a.quality ? (
        <>
          <AiSectionCard content={a.quality.content} model={a.quality.model} generatedAt={a.quality.generatedAt} />
          <Btn icon={<RefreshCw size={14} />} onClick={onGenerate} disabled={busy}>
            {busy ? "Generating…" : "Regenerate"}
          </Btn>
        </>
      ) : (
        <GenerateBanner
          label="code quality review"
          offline={offlineQuality(a)}
          onGenerate={onGenerate}
          busy={busy}
          hasKey={hasKey}
          onOpenSettings={onOpenSettings}
        />
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// File detail
// ---------------------------------------------------------------------------

function FileDetailView({
  a,
  path,
  readFile,
  onAskFile,
}: {
  a: ProjectAnalysis;
  path: string;
  readFile: (p: string) => Promise<string | null>;
  onAskFile: (path: string, content: string, explain?: boolean) => void;
}) {
  const [content, setContent] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const node = useMemo(() => {
    const walk = (nodes: typeof a.tree): (typeof a.tree)[number] | undefined => {
      for (const n of nodes) {
        if (n.path === path) return n;
        const hit = walk(n.children);
        if (hit) return hit;
      }
      return undefined;
    };
    return walk(a.tree);
  }, [a.tree, path]);

  useEffect(() => {
    let alive = true;
    setLoading(true);
    setContent(null);
    readFile(path).then((t) => {
      if (!alive) return;
      setContent(t);
      setLoading(false);
    });
    return () => {
      alive = false;
    };
  }, [path, readFile]);

  return (
    <div className="animate-fadeUp space-y-4">
      <Card className="p-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <FileText size={15} className="shrink-0 text-gold-400" />
              <span className="truncate font-mono text-[14px] font-medium text-zinc-100">{path}</span>
            </div>
            <div className="mt-1.5 flex items-center gap-2">
              {node && <Badge>{node.size ? fmtBytes(node.size) : "—"}</Badge>}
              <Badge tone="blue">file</Badge>
            </div>
          </div>
          <div className="flex gap-2">
            <Btn variant="primary" icon={<Zap size={14} />} onClick={() => content !== null && onAskFile(path, content, true)} disabled={content === null}>
              Explain with AI
            </Btn>
            <Btn icon={<Sparkles size={14} />} onClick={() => content !== null && onAskFile(path, content, false)} disabled={content === null}>
              Ask about this file
            </Btn>
          </div>
        </div>
      </Card>

      <Card className="overflow-hidden">
        {loading ? (
          <div className="flex items-center justify-center gap-2 py-16 text-zinc-500">
            <Loader2 size={18} className="animate-spin text-gold-400" /> Loading file…
          </div>
        ) : content === null ? (
          <div className="p-8 text-center">
            <EmptyState
              icon={<FileText size={22} />}
              title="Content unavailable"
              body={
                "This file couldn't be read (binary, too large, or loaded from history without the original source). Re-import the project to read contents — you can still ask the assistant about it."
              }
            />
          </div>
        ) : (
          <>
            <div className="flex items-center justify-between border-b border-white/5 px-4 py-2">
              <span className="text-[11px] text-zinc-500">First {Math.min(400, content.split("\n").length)} of {content.split("\n").length} lines</span>
              <span className="text-[11px] text-zinc-600">{(content.length / 1024).toFixed(1)} KB</span>
            </div>
            <pre className="max-h-[60vh] overflow-auto p-4 font-mono text-[12px] leading-relaxed text-zinc-300">
              {content.split("\n").slice(0, 400).map((l, i) => (
                <div key={i} className="flex">
                  <span className="w-10 shrink-0 select-none pr-3 text-right text-zinc-700">{i + 1}</span>
                  <span className="whitespace-pre-wrap">{l || " "}</span>
                </div>
              ))}
            </pre>
          </>
        )}
      </Card>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main center
// ---------------------------------------------------------------------------

const TABS: Array<{ id: Tab; label: string; icon: React.ReactNode }> = [
  { id: "overview", label: "Overview", icon: <LayoutDashboard size={14} /> },
  { id: "architecture", label: "Architecture", icon: <Network size={14} /> },
  { id: "dependencies", label: "Dependencies", icon: <Boxes size={14} /> },
  { id: "diagram", label: "Diagram", icon: <Workflow size={14} /> },
  { id: "security", label: "Security", icon: <ShieldAlert size={14} /> },
  { id: "quality", label: "Quality", icon: <BarChart3 size={14} /> },
];

export function Center({
  a,
  tab,
  setTab,
  selectedFile,
  readFile,
  onAskFile,
  onGenerate,
  genBusy,
  hasKey,
  onOpenSettings,
}: {
  a: ProjectAnalysis;
  tab: Tab;
  setTab: (t: Tab) => void;
  selectedFile: string | null;
  readFile: (p: string) => Promise<string | null>;
  onAskFile: (path: string, content: string, explain?: boolean) => void;
  onGenerate: (section: "architecture" | "quality" | "readme") => void;
  genBusy: "architecture" | "quality" | "readme" | null;
  hasKey: boolean;
  onOpenSettings: () => void;
}) {
  const tabs = selectedFile ? [...TABS, { id: "file" as Tab, label: "File", icon: <FileText size={14} /> }] : TABS;

  return (
    <main className="flex min-w-0 flex-1 flex-col bg-ink-900">
      <div className="flex shrink-0 items-center gap-1 overflow-x-auto border-b border-white/5 px-4 pt-2.5">
        {tabs.map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className={cn(
              "flex items-center gap-1.5 whitespace-nowrap rounded-t-lg border-b-2 px-3.5 py-2.5 text-[13px] font-medium transition-all",
              tab === t.id
                ? "border-gold-400 text-gold-200"
                : "border-transparent text-zinc-500 hover:text-zinc-200"
            )}
          >
            {t.icon}
            {t.label}
            {t.id === "security" && a.security.filter((f) => f.severity === "high").length > 0 && (
              <span className="ml-0.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-red-500/80 px-1 text-[9px] font-bold text-white">
                {a.security.filter((f) => f.severity === "high").length}
              </span>
            )}
          </button>
        ))}
      </div>

      <div className="min-h-0 flex-1 overflow-y-auto p-5">
        {tab === "overview" && <OverviewView a={a} />}
        {tab === "architecture" && (
          <ArchitectureView
            a={a}
            onGenerate={() => onGenerate("architecture")}
            busy={genBusy === "architecture"}
            hasKey={hasKey}
            onOpenSettings={onOpenSettings}
            onGenerateReadme={() => onGenerate("readme")}
            readmeBusy={genBusy === "readme"}
          />
        )}
        {tab === "dependencies" && <DepsView a={a} />}
        {tab === "diagram" && <DiagramView a={a} />}
        {tab === "security" && <SecurityView a={a} />}
        {tab === "quality" && (
          <QualityView
            a={a}
            onGenerate={() => onGenerate("quality")}
            busy={genBusy === "quality"}
            hasKey={hasKey}
            onOpenSettings={onOpenSettings}
          />
        )}
        {tab === "file" && selectedFile && <FileDetailView a={a} path={selectedFile} readFile={readFile} onAskFile={onAskFile} />}
      </div>
    </main>
  );
}
