// Report export: full Markdown report, JSON dump, and a print-to-PDF flow.
import type { ProjectAnalysis, SecurityFinding } from "../types";
import { fmtBytes, fmtCount, fmtTime } from "../store";
import { renderMarkdown } from "../markdown";

export function reportMarkdown(a: ProjectAnalysis): string {
  const lines: string[] = [];
  lines.push(`# RECON AI report — ${a.name}`);
  lines.push("");
  lines.push(`> Generated ${fmtTime(a.importedAt)} · Source: ${a.label} · ${fmtCount(a.fileCount)} files · ${fmtBytes(a.totalSize)}`);
  lines.push("");
  lines.push("## Overview");
  lines.push("");
  if (a.readmePreview) lines.push(`**README preview:**\n\n${a.readmePreview.slice(0, 1500)}\n`);
  lines.push("### Languages");
  lines.push("");
  if (a.languages.length) {
    lines.push("| Language | Files | Confidence |");
    lines.push("| --- | --- | --- |");
    for (const l of a.languages) lines.push(`| ${l.name} | ${l.files} | ${Math.round(l.confidence * 100)}% |`);
  } else {
    lines.push("No source languages confidently detected.");
  }
  lines.push("");
  lines.push("### Frameworks & runtimes");
  lines.push("");
  lines.push(a.frameworks.length ? a.frameworks.map((f) => `- **${f.name}** — ${Math.round(f.confidence * 100)}% (${f.source})`).join("\n") : "None confidently detected.");
  lines.push("");
  lines.push("### Entry points");
  lines.push("");
  lines.push(a.entryPoints.length ? a.entryPoints.map((e) => `- \`${e}\``).join("\n") : "None detected.");
  lines.push("");
  lines.push("### Build systems");
  lines.push("");
  lines.push(a.buildSystems.length ? a.buildSystems.join(", ") : "None detected.");
  lines.push("");
  lines.push("## Architecture");
  lines.push("");
  lines.push(a.architecture ? a.architecture.content : "AI architecture summary not generated yet.");
  lines.push("");
  lines.push("## Dependencies");
  lines.push("");
  lines.push(`- Runtime: ${a.depSummary.runtime}`);
  lines.push(`- Development: ${a.depSummary.dev}`);
  if (a.depSummary.unpinned.length) lines.push(`- Unpinned: ${a.depSummary.unpinned.join(", ")}`);
  if (a.depSummary.duplicates.length) lines.push(`- Duplicates across manifests: ${a.depSummary.duplicates.join(", ")}`);
  lines.push("");
  if (a.deps.length) {
    lines.push("| Package | Version | Kind | Manifest |");
    lines.push("| --- | --- | --- | --- |");
    for (const d of a.deps.slice(0, 200)) lines.push(`| ${d.name} | ${d.version} | ${d.kind} | ${d.manifest} |`);
  } else {
    lines.push("No dependency manifests parsed.");
  }
  lines.push("");
  lines.push("## Security review (heuristic)");
  lines.push("");
  lines.push("> Pattern-based findings only — not a guarantee. Review manually before trusting.");
  lines.push("");
  if (a.security.length) {
    lines.push("| Severity | Category | Finding | Location |");
    lines.push("| --- | --- | --- | --- |");
    for (const f of a.security.slice(0, 120)) {
      const loc = f.file ? `${f.file}${f.line ? `:${f.line}` : ""}` : "—";
      lines.push(`| ${f.severity} | ${f.category} | ${f.message.replace(/\|/g, "\\|")} | ${loc} |`);
    }
  } else {
    lines.push("No findings in the sampled files.");
  }
  lines.push("");
  lines.push(`Scan coverage: ${a.scanStats.filesScanned} files / ${fmtBytes(a.scanStats.bytesScanned)} scanned.`);
  lines.push("");
  lines.push("## Code quality");
  lines.push("");
  lines.push(a.quality ? a.quality.content : "AI quality review not generated yet.");
  lines.push("");
  lines.push("## Notes");
  lines.push("");
  lines.push(a.notes.map((n) => `- ${n}`).join("\n"));
  lines.push("");
  lines.push("---");
  lines.push("*Generated by RECON AI (K1NG BRONXO). Static analysis only; no protections were bypassed.*");
  return lines.join("\n");
}

export function reportJson(a: ProjectAnalysis): string {
  return JSON.stringify(
    {
      meta: { app: "RECON AI", generatedAt: new Date(a.importedAt).toISOString(), name: a.name, source: a.label, fileCount: a.fileCount, totalSize: a.totalSize },
      overview: {
        languages: a.languages,
        frameworks: a.frameworks,
        entryPoints: a.entryPoints,
        buildSystems: a.buildSystems,
        configFiles: a.configFiles,
        manifests: a.manifests,
      },
      dependencies: { summary: a.depSummary, deps: a.deps },
      security: { findings: a.security, scanStats: a.scanStats },
      architecture: a.architecture,
      quality: a.quality,
      readme: a.readme,
      notes: a.notes,
    },
    null,
    2
  );
}

export function downloadText(filename: string, text: string, mime = "text/plain"): void {
  const blob = new Blob([text], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

export function printReport(a: ProjectAnalysis): void {
  const md = reportMarkdown(a);
  const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>RECON AI — ${a.name}</title>
<style>
  body { font-family: system-ui, -apple-system, "Segoe UI", sans-serif; max-width: 820px; margin: 40px auto; padding: 0 24px; color: #1a1a1a; line-height: 1.6; }
  h1 { border-bottom: 3px solid #d4af37; padding-bottom: 8px; }
  h2 { border-bottom: 1px solid #ddd; padding-bottom: 4px; margin-top: 28px; }
  table { border-collapse: collapse; width: 100%; font-size: 13px; }
  th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; }
  th { background: #f5f0df; }
  code { background: #f3f3f3; padding: 1px 5px; border-radius: 4px; font-size: 12px; }
  pre { background: #f8f8f8; padding: 12px; border-radius: 8px; overflow-x: auto; font-size: 12px; }
  blockquote { border-left: 4px solid #d4af37; margin: 12px 0; padding: 2px 14px; color: #555; }
  a { color: #b8962e; }
  @media print { body { margin: 0; } }
</style>
</head>
<body>${renderMarkdown(md)}</body>
</html>`;
  const w = window.open("", "_blank");
  if (!w) {
    alert("Your environment blocked the print window. Use Export → Markdown instead.");
    return;
  }
  w.document.open();
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => {
    w.print();
  }, 500);
}

export function securityLine(f: SecurityFinding): string {
  return `${f.severity.toUpperCase()} [${f.category}] ${f.message}${f.file ? ` — ${f.file}${f.line ? `:${f.line}` : ""}` : ""}`;
}
